import kidsTraditionalimage1 from "../assets/kidsPage/kidstraditionaldresses/kidspagetraditionalimage1.webp"
import kidsTraditionalimage2 from "../assets/kidsPage/kidstraditionaldresses/kidspagetraditionalimage2.webp"
import kidsTraditionalimage3 from "../assets/kidsPage/kidstraditionaldresses/kidspagetraditionalimage3.webp"
import kidsTraditionalimage4 from "../assets/kidsPage/kidstraditionaldresses/kidspagetraditionalimage4.webp"
import kidsTraditionalimage5 from "../assets/kidsPage/kidstraditionaldresses/kidspagetraditionalimage5.jpg"
import kidshoddieimage1 from "../assets/kidsPage/kidshoddies/kidspagehoddieimage1.webp"
import kidshoddieimage2 from "../assets/kidsPage/kidshoddies/kidspagehoddieimage2.webp"
import kidshoddieimage3 from "../assets/kidsPage/kidshoddies/kidspagehoddieimage3.webp"
import kidshoddieimage4 from "../assets/kidsPage/kidshoddies/kidspagehoddieimage4.webp"
import kidshoddieimage5 from "../assets/kidsPage/kidshoddies/kidspagehoddieimage5.webp"
import kidsgirldressimage1 from "../assets/kidsPage/babygirldresses/kidspagegirldressimage1.avif"
import kidsgirldressimage2 from "../assets/kidsPage/babygirldresses/kidspagegirldressimage2.avif"
import kidsgirldressimage3 from "../assets/kidsPage/babygirldresses/kidspagegirldressimage3.avif"
import kidsgirldressimage4 from "../assets/kidsPage/babygirldresses/kidspagegirldressimage4.avif"
import kidsgirldressimage5 from "../assets/kidsPage/babygirldresses/kidspagegirldressimage5.avif"
import kidsboydressimage1 from "../assets/kidsPage/babyboydresses/kidspageboydressimage1.webp"
import kidsboydressimage2 from "../assets/kidsPage/babyboydresses/kidspageboydressimage2.webp"
import kidsboydressimage3 from "../assets/kidsPage/babyboydresses/kidspageboydressimage3.webp"
import kidsboydressimage4 from "../assets/kidsPage/babyboydresses/kidspageboydressimage4.webp"
import kidsboydressimage5 from "../assets/kidsPage/babyboydresses/kidspageboydressimage5.webp"
import kidstshirtimage1 from "../assets/kidsPage/kidstshirts/kidspagetshirtimage1.webp"
import kidstshirtimage2 from "../assets/kidsPage/kidstshirts/kidspagetshirtimage2.webp"
import kidstshirtimage3 from "../assets/kidsPage/kidstshirts/kidspagetshirtimage3.webp"
import kidstshirtimage4 from "../assets/kidsPage/kidstshirts/kidspagetshirtimage4.webp"
import kidstshirtimage5 from "../assets/kidsPage/kidstshirts/kidspagetshirtimage5.webp"




export const kidspagesData = [
  // Traditional Wear
  {
    id: 3011,
    name: "BownBee",
    description: "Ethnic Kurta Pajama Set for Boys",
    detailedDescription: "A charming ethnic kurta pajama set from BownBee, perfect for festive occasions and family gatherings. Made with comfortable fabric, ensuring your little one stays happy.",
    price: 850,
    image: kidsTraditionalimage1,
    category: "traditional",
    offers: true,
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"],
    averageRating: 4.5,
    totalRatings: 75,
    customerReviews: [
      { id: 1, user: "Rina S.", rating: 5, review: "Adorable set, my son looked so cute for the Diwali party!" },
      { id: 2, user: "Alok V.", rating: 4, review: "Good quality and comfortable. Fits true to size." },
      { id: 3, user: "Priya K.", rating: 4, review: "Nice traditional wear for kids. A bit pricey but worth it." },
    ],
  },
  {
    id: 3012,
    name: "Tiber Taber",
    description: "Festive Dhoti Kurta Set for Boys",
    detailedDescription: "Elevate your child's festive look with this elegant dhoti kurta set from Tiber Taber. Designed for comfort and style, perfect for weddings and cultural events.",
    price: 990,
    image: kidsTraditionalimage2,
    category: "traditional",
    offers: false,
    sizes: ["1-2Y", "2-3Y", "3-4Y"],
    averageRating: 4.7,
    totalRatings: 60,
    customerReviews: [
      { id: 1, user: "Seema M.", rating: 5, review: "Absolutely loved it! My nephew looked like a prince." },
      { id: 2, user: "Gaurav P.", rating: 4, review: "Good quality fabric and stitching. A bit difficult to iron." },
      { id: 3, user: "Nisha R.", rating: 5, review: "Perfect for traditional functions. Very stylish." },
    ],
  },
  {
    id: 3013,
    name: "BIBA Kids",
    description: "Printed Lehenga Choli Set",
    detailedDescription: "A beautiful printed lehenga choli set for girls from BIBA Kids. Ideal for festive occasions, featuring vibrant prints and comfortable fabric for easy movement.",
    price: 1100,
    image: kidsTraditionalimage3,
    category: "traditional",
    offers: true,
    sizes: ["4-5Y", "5-6Y", "6-7Y", "7-8Y"],
    averageRating: 4.6,
    totalRatings: 85,
    customerReviews: [
      { id: 1, user: "Anjali D.", rating: 5, review: "My daughter adored this! The colors are so pretty." },
      { id: 2, user: "Rajesh S.", rating: 4, review: "Good for the price, decent quality. My niece looked lovely." },
      { id: 3, user: "Smita G.", rating: 4, review: "Comfortable material for kids. Recommended for light functions." },
    ],
  },
  {
    id: 3014,
    name: "Aarika",
    description: "Traditional Dress with Dupatta",
    detailedDescription: "This elegant traditional dress with a matching dupatta from Aarika is perfect for young girls attending special events. Designed with intricate details and comfortable fabric.",
    price: 1250,
    image: kidsTraditionalimage4,
    category: "traditional",
    offers: false,
    sizes: ["6-7Y", "7-8Y", "8-9Y"],
    averageRating: 4.4,
    totalRatings: 50,
    customerReviews: [
      { id: 1, user: "Kiran J.", rating: 5, review: "Beautiful dress, my daughter felt like a princess." },
      { id: 2, user: "Vivek L.", rating: 4, review: "The detailing is nice, but the dupatta is a bit slippery." },
      { id: 3, user: "Arti P.", rating: 4, review: "Good for a one-time event. Looks very festive." },
    ],
  },
  {
    id: 3015,
    name: "Hopscotch",
    description: "Embroidered Sherwani Suit",
    detailedDescription: "A dashing embroidered sherwani suit from Hopscotch, perfect for formal traditional occasions for boys. Features intricate embroidery and a comfortable fit.",
    price: 1500,
    image: kidsTraditionalimage5,
    category: "traditional",
    offers: true,
    sizes: ["5-6Y", "6-7Y", "7-8Y", "8-9Y"],
    averageRating: 4.8,
    totalRatings: 45,
    customerReviews: [
      { id: 1, user: "Sonal C.", rating: 5, review: "Excellent quality and stunning embroidery. My son loved it." },
      { id: 2, user: "Amit K.", rating: 5, review: "Perfect for weddings! Looks very grand." },
      { id: 3, user: "Deepika V.", rating: 4, review: "A bit heavy for daily wear, but amazing for special occasions." },
    ],
  },

  // Hoodies
  {
    id: 3021,
    name: "Mothercare",
    description: "Soft Cotton Hoodie for Kids",
    detailedDescription: "Keep your child warm and cozy with this soft cotton hoodie from Mothercare. Perfect for everyday wear, offering comfort and gentle warmth.",
    price: 699,
    image: kidshoddieimage1,
    category: "hoddie",
    offers: false,
    sizes: ["6-12M", "12-18M", "18-24M", "2-3Y"],
    averageRating: 4.4,
    totalRatings: 90,
    customerReviews: [
      { id: 1, user: "Ria S.", rating: 5, review: "Super soft and gentle on baby's skin. Love it!" },
      { id: 2, user: "Kunal M.", rating: 4, review: "Good for mild winters. True to Mothercare's quality." },
      { id: 3, user: "Preeti N.", rating: 4, review: "Cute design and comfortable. Washes well." },
    ],
  },
  {
    id: 3022,
    name: "Mini Klub",
    description: "Printed Zip-Up Hoodie",
    detailedDescription: "A playful printed zip-up hoodie from Mini Klub, ideal for adding a fun layer to your child's outfit. Easy to wear and comfortable for all-day play.",
    price: 750,
    image: kidshoddieimage2,
    category: "hoddie",
    offers: true,
    sizes: ["2-3Y", "3-4Y", "4-5Y"],
    averageRating: 4.2,
    totalRatings: 80,
    customerReviews: [
      { id: 1, user: "Divya P.", rating: 4, review: "My son loves the print! Good for layering." },
      { id: 2, user: "Rahul T.", rating: 3, review: "Decent hoodie, but the zipper can be a bit sticky sometimes." },
      { id: 3, user: "Shweta B.", rating: 4, review: "Comfortable and colorful. Good value." },
    ],
  },
  {
    id: 3023,
    name: "Babyhug",
    description: "Cute Ears Fleece Hoodie",
    detailedDescription: "This adorable fleece hoodie from Babyhug features cute ear details, making your little one even more charming. Provides warmth and comfort for cooler days.",
    price: 800,
    image: kidshoddieimage3,
    category: "hoddie",
    offers: false,
    sizes: ["0-6M", "6-12M", "12-18M"],
    averageRating: 4.7,
    totalRatings: 100,
    customerReviews: [
      { id: 1, user: "Ananya H.", rating: 5, review: "So cute! And surprisingly warm. Love the ears." },
      { id: 2, user: "Varun D.", rating: 5, review: "Bought as a gift, the parents loved it for their baby." },
      { id: 3, user: "Neha C.", rating: 4, review: "Soft material, perfect for newborns. Highly recommend." },
    ],
  },
  {
    id: 3024,
    name: "Carter's",
    description: "Cozy Winter Hoodie",
    detailedDescription: "A super cozy winter hoodie from Carter's, designed to provide ultimate warmth and comfort for your child during colder months. Known for its quality and durability.",
    price: 900,
    image: kidshoddieimage4,
    category: "hoddie",
    offers: true,
    sizes: ["1-2Y", "2-3Y", "3-4Y", "4-5Y"],
    averageRating: 4.8,
    totalRatings: 110,
    customerReviews: [
      { id: 1, user: "Samir K.", rating: 5, review: "Excellent for winter. Very thick and warm." },
      { id: 2, user: "Pooja V.", rating: 5, review: "Carter's quality is unmatched. This hoodie is perfect." },
      { id: 3, user: "Vikas G.", rating: 4, review: "Holds up well after multiple washes. Worth the price." },
    ],
  },
  {
    id: 3025,
    name: "H&M Kids",
    description: "Minimalist Full-Sleeve Hoodie",
    detailedDescription: "A stylish minimalist full-sleeve hoodie from H&M Kids, perfect for a modern and comfortable look. Easy to pair with any outfit.",
    price: 880,
    image: kidshoddieimage5,
    category: "hoddie",
    offers: false,
    sizes: ["5-6Y", "6-7Y", "7-8Y"],
    averageRating: 4.3,
    totalRatings: 70,
    customerReviews: [
      { id: 1, user: "Rohan J.", rating: 4, review: "Simple and stylish. My daughter wears it all the time." },
      { id: 2, user: "Smriti L.", rating: 4, review: "Good for everyday use. Material is soft." },
      { id: 3, user: "Ajay C.", rating: 3, review: "A bit thin for very cold weather, but good otherwise." },
    ],
  },

  // Baby Girl Dresses
  {
    id: 3031,
    name: "Aarika",
    description: "Princess Net Frock Dress",
    detailedDescription: "A beautiful princess net frock dress from Aarika, perfect for birthday parties and special occasions. Features delicate net fabric and a charming design.",
    price: 1050,
    image: kidsgirldressimage1,
    category: "babygirldress",
    offers: true,
    sizes: ["1-2Y", "2-3Y", "3-4Y", "4-5Y"],
    averageRating: 4.6,
    totalRatings: 105,
    customerReviews: [
      { id: 1, user: "Priya S.", rating: 5, review: "My daughter looked like a fairy! Absolutely gorgeous." },
      { id: 2, user: "Ankit R.", rating: 4, review: "Good quality dress. The net is soft and not scratchy." },
      { id: 3, user: "Divya M.", rating: 4, review: "Perfect for parties, but needs delicate washing." },
    ],
  },
  {
    id: 3032,
    name: "Cherry Crumble",
    description: "Floral Party Dress",
    detailedDescription: "A delightful floral party dress from Cherry Crumble, ideal for any celebration. Features a vibrant floral print and comfortable fabric for active kids.",
    price: 950,
    image: kidsgirldressimage2,
    category: "babygirldress",
    offers: false,
    sizes: ["2-3Y", "3-4Y", "4-5Y", "5-6Y"],
    averageRating: 4.5,
    totalRatings: 95,
    customerReviews: [
      { id: 1, user: "Rina D.", rating: 5, review: "Beautiful dress, my daughter loves twirling in it." },
      { id: 2, user: "Sumit H.", rating: 4, review: "Good for summer parties. The print is very cheerful." },
      { id: 3, user: "Shalini J.", rating: 4, review: "Comfortable and stylish. Highly recommend." },
    ],
  },
  {
    id: 3033,
    name: "Kookie Kids",
    description: "Ruffle Sleeveless Dress",
    detailedDescription: "A cute ruffle sleeveless dress from Kookie Kids, perfect for everyday wear or casual outings. Soft fabric and playful ruffles make it a favorite.",
    price: 880,
    image: kidsgirldressimage3,
    category: "babygirldress",
    offers: true,
    sizes: ["1-2Y", "2-3Y", "3-4Y"],
    averageRating: 4.2,
    totalRatings: 80,
    customerReviews: [
      { id: 1, user: "Deepak S.", rating: 4, review: "Nice everyday dress for my niece. Good fabric." },
      { id: 2, user: "Pooja A.", rating: 3, review: "A bit loose fit, but the ruffles are cute." },
      { id: 3, user: "Rahul M.", rating: 4, review: "Comfortable and easy to wear. Happy with the purchase." },
    ],
  },
  {
    id: 3034,
    name: "Fiffy",
    description: "Cotton Printed Dress for Girls",
    detailedDescription: "A comfortable cotton printed dress for girls from Fiffy, ideal for daily wear. Features charming prints and breathable fabric for active play.",
    price: 790,
    image: kidsgirldressimage4,
    category: "babygirldress",
    offers: false,
    sizes: ["0-6M", "6-12M", "12-18M", "18-24M"],
    averageRating: 4.0,
    totalRatings: 70,
    customerReviews: [
      { id: 1, user: "Kavita N.", rating: 4, review: "Good for home wear. The print is cute." },
      { id: 2, user: "Manish R.", rating: 3, review: "Fabric is okay for the price. Simple daily dress." },
      { id: 3, user: "Divya C.", rating: 4, review: "Easy to wash and maintain. Baby looks comfortable." },
    ],
  },
  {
    id: 3035,
    name: "FirstCry",
    description: "Lace Fit & Flare Party Frock",
    detailedDescription: "A delightful lace fit & flare party frock from FirstCry, perfect for special occasions. Features intricate lace detailing and a comfortable fit for your little one.",
    price: 1120,
    image: kidsgirldressimage5,
    category: "babygirldress",
    offers: true,
    sizes: ["3-4Y", "4-5Y", "5-6Y"],
    averageRating: 4.7,
    totalRatings: 65,
    customerReviews: [
      { id: 1, user: "Aditi S.", rating: 5, review: "Gorgeous dress! The lace is beautiful and soft." },
      { id: 2, user: "Rajesh K.", rating: 5, review: "Perfect for a birthday party. Highly recommended." },
      { id: 3, user: "Poonam D.", rating: 4, review: "My daughter loves it, but it's a bit delicate." },
    ],
  },

  // Baby Boy Dresses
  {
    id: 3041,
    name: "Babyoye",
    description: "Dungaree and T-shirt Set",
    detailedDescription: "A charming dungaree and T-shirt set from Babyoye, perfect for active little boys. Comfortable and stylish, ideal for playtime and casual outings.",
    price: 890,
    image: kidsboydressimage1,
    category: "babyboydress",
    offers: true,
    sizes: ["6-12M", "12-18M", "18-24M"],
    averageRating: 4.3,
    totalRatings: 90,
    customerReviews: [
      { id: 1, user: "Sonal M.", rating: 5, review: "So cute and comfortable for my baby boy. Easy to put on." },
      { id: 2, user: "Anuj P.", rating: 4, review: "Good quality fabric. The dungaree is adorable." },
      { id: 3, user: "Ria S.", rating: 4, review: "Practical and stylish. A great everyday outfit." },
    ],
  },
  {
    id: 3042,
    name: "Little Kangaroos",
    description: "2-Piece Shirt and Shorts Set",
    detailedDescription: "A trendy 2-piece shirt and shorts set from Little Kangaroos, perfect for your little adventurer. Comfortable and stylish for summer days.",
    price: 780,
    image: kidsboydressimage2,
    category: "babyboydress",
    offers: false,
    sizes: ["1-2Y", "2-3Y", "3-4Y"],
    averageRating: 4.1,
    totalRatings: 85,
    customerReviews: [
      { id: 1, user: "Harish G.", rating: 4, review: "Nice set for summer. The shirt is very soft." },
      { id: 2, user: "Meera C.", rating: 3, review: "Good for the price, but the shorts fabric is a bit thin." },
      { id: 3, user: "Vikram D.", rating: 4, review: "Comfortable and looks good on my son." },
    ],
  },
  {
    id: 3043,
    name: "Juniors",
    description: "Plaid Shirt with Jeans Combo",
    detailedDescription: "A stylish plaid shirt with jeans combo from Juniors, offering a smart casual look for boys. Comfortable and durable for everyday wear.",
    price: 999,
    image: kidsboydressimage3,
    category: "babyboydress",
    offers: true,
    sizes: ["4-5Y", "5-6Y", "6-7Y"],
    averageRating: 4.5,
    totalRatings: 70,
    customerReviews: [
      { id: 1, user: "Suresh P.", rating: 5, review: "Great combo! My son looks very smart in it." },
      { id: 2, user: "Deepa R.", rating: 4, review: "Good quality jeans and shirt. A bit snug fit for my active boy." },
      { id: 3, user: "Prakash V.", rating: 4, review: "Stylish and comfortable. Perfect for family outings." },
    ],
  },
  {
    id: 3044,
    name: "Peppermint",
    description: "Full-Sleeve Boys Outfit Set",
    detailedDescription: "A cozy full-sleeve boys outfit set from Peppermint, ideal for cooler weather. Provides warmth and comfort while maintaining a stylish look.",
    price: 850,
    image: kidsboydressimage4,
    category: "babyboydress",
    offers: false,
    sizes: ["2-3Y", "3-4Y", "4-5Y"],
    averageRating: 4.2,
    totalRatings: 60,
    customerReviews: [
      { id: 1, user: "Rakesh S.", rating: 4, review: "Good for winter. The fabric is soft." },
      { id: 2, user: "Kavya M.", rating: 3, review: "Decent set, but the colors are a bit dull." },
      { id: 3, user: "Arjun N.", rating: 4, review: "Comfortable and practical for everyday wear." },
    ],
  },
  {
    id: 3045,
    name: "ToffyHouse",
    description: "Cotton Shirt & Pant Combo",
    detailedDescription: "A comfortable cotton shirt & pant combo from ToffyHouse, perfect for daily wear or casual outings. Soft and breathable fabric ensures all-day comfort.",
    price: 930,
    image: kidsboydressimage5,
    category: "babyboydress",
    offers: true,
    sizes: ["1-2Y", "2-3Y", "3-4Y"],
    averageRating: 4.4,
    totalRatings: 75,
    customerReviews: [
      { id: 1, user: "Anjali L.", rating: 5, review: "Very good quality cotton. My son loves it." },
      { id: 2, user: "Rahul K.", rating: 4, review: "Comfortable combo, easy to dress up or down." },
      { id: 3, user: "Smita V.", rating: 4, review: "Nice for daily wear. Holds up well after washing." },
    ],
  },

  // T-Shirts
  {
    id: 3051,
    name: "Babyhug",
    description: "Cartoon Printed T-Shirt",
    detailedDescription: "A fun cartoon printed T-shirt from Babyhug, designed to delight your little one. Made from soft cotton for comfortable everyday wear.",
    price: 350,
    image: kidstshirtimage1,
    category: "tshirt",
    offers: false,
    sizes: ["6-12M", "12-18M", "18-24M"],
    averageRating: 4.0,
    totalRatings: 150,
    customerReviews: [
      { id: 1, user: "Priya P.", rating: 4, review: "Cute print, my baby loves the cartoons." },
      { id: 2, user: "Amit S.", rating: 3, review: "Good for the price, but the fabric is a bit thin." },
      { id: 3, user: "Rina J.", rating: 4, review: "Comfortable and easy to wash. Happy with the purchase." },
    ],
  },
  {
    id: 3052,
    name: "Lilliput",
    description: "Solid Round Neck T-Shirt",
    detailedDescription: "A versatile solid round neck T-shirt from Lilliput, a basic essential for every child's wardrobe. Made from soft cotton for comfort.",
    price: 300,
    image: kidstshirtimage2,
    category: "tshirt",
    offers: true,
    sizes: ["2-3Y", "3-4Y", "4-5Y"],
    averageRating: 4.2,
    totalRatings: 130,
    customerReviews: [
      { id: 1, user: "Nisha V.", rating: 4, review: "Good basic tee, multiple colors available." },
      { id: 2, user: "Sanjay B.", rating: 4, review: "Comfortable and durable. Good for everyday use." },
      { id: 3, user: "Deepika G.", rating: 3, review: "Simple but effective. No complaints." },
    ],
  },
  {
    id: 3053,
    name: "Mini Klub",
    description: "Striped Cotton T-Shirt",
    detailedDescription: "A classic striped cotton T-shirt from Mini Klub, perfect for a casual and stylish look. Soft and breathable for all-day comfort.",
    price: 399,
    image: kidstshirtimage3,
    category: "tshirt",
    offers: false,
    sizes: ["1-2Y", "2-3Y", "3-4Y"],
    averageRating: 4.1,
    totalRatings: 110,
    customerReviews: [
      { id: 1, user: "Prakash K.", rating: 4, review: "Nice stripes, good for daily wear." },
      { id: 2, user: "Smita H.", rating: 3, review: "The fabric could be softer, but it's okay." },
      { id: 3, user: "Rajesh L.", rating: 4, review: "Comfortable and fits well. Happy with the purchase." },
    ],
  },
  {
    id: 3054,
    name: "FirstCry",
    description: "Dinosaur Print T-Shirt",
    detailedDescription: "A fun dinosaur print T-shirt from FirstCry, sure to be a hit with dinosaur-loving kids. Made from comfortable cotton for play and comfort.",
    price: 450,
    image: kidstshirtimage4,
    category: "tshirt",
    offers: true,
    sizes: ["4-5Y", "5-6Y", "6-7Y"],
    averageRating: 4.5,
    totalRatings: 100,
    customerReviews: [
      { id: 1, user: "Arjun V.", rating: 5, review: "My son absolutely loves this t-shirt! Great print." },
      { id: 2, user: "Meera D.", rating: 4, review: "Good quality and the print hasn't faded after washes." },
      { id: 3, user: "Gaurav S.", rating: 4, review: "Comfortable and very appealing to kids." },
    ],
  },
  {
    id: 3055,
    name: "Marks & Spencer",
    description: "Colorful Crew Neck T-Shirt",
    detailedDescription: "A vibrant colorful crew neck T-shirt from Marks & Spencer, offering excellent quality and comfort. A versatile piece for any child's wardrobe.",
    price: 500,
    image: kidstshirtimage5,
    category: "tshirt",
    offers: false,
    sizes: ["5-6Y", "6-7Y", "7-8Y"],
    averageRating: 4.7,
    totalRatings: 120,
    customerReviews: [
      { id: 1, user: "Kajal P.", rating: 5, review: "Fantastic quality! The colors are bright and durable." },
      { id: 2, user: "Rohit N.", rating: 5, review: "Soft fabric, perfect for sensitive skin." },
      { id: 3, user: "Swati R.", rating: 4, review: "A bit expensive for a t-shirt, but the quality justifies it." },
    ],
  },
];