import menpagecasual1 from "../assets/mensPage/casualshirts/men-page-casualshirt1.avif"
import menpagecasual2 from "../assets/mensPage/casualshirts/men-page-casualshirt2.avif"
import menpagecasual3 from "../assets/mensPage/casualshirts/men-page-casualshirt3.avif"
import menpagecasual4 from "../assets/mensPage/casualshirts/men-page-casualshirt4.avif"
import menpagecasual5 from "../assets/mensPage/casualshirts/men-page-casualshirt5.avif"
import menpageformal1 from "../assets/mensPage/formalshirts/men-page-formalshirt1.avif"
import menpageformal2 from "../assets/mensPage/formalshirts/men-page-formalshirt2.avif"
import menpageformal3 from "../assets/mensPage/formalshirts/men-page-formalshirt3.avif"
import menpageformal4 from "../assets/mensPage/formalshirts/men-page-formalshirt4.avif"
import menpageformal5 from "../assets/mensPage/formalshirts/men-page-formalshirt5.avif"
import menpagetradition1 from "../assets/mensPage/traditional/men-page-tradition1.avif"
import menpagetradition2 from "../assets/mensPage/traditional/men-page-tradition2.avif"
import menpagetradition3 from "../assets/mensPage/traditional/men-page-tradition3.avif"
import menpagetradition4 from "../assets/mensPage/traditional/men-page-tradition4.avif"
import menpagetradition5 from "../assets/mensPage/traditional/men-page-tradition5.avif"
import menpagehoddie1 from "../assets/mensPage/hoddies/men-page-hoddie1.webp"
import menpagehoddie2 from "../assets/mensPage/hoddies/men-page-hoddie2.webp"
import menpagehoddie3 from "../assets/mensPage/hoddies/men-page-hoddie3.webp"
import menpagehoddie4 from "../assets/mensPage/hoddies/men-page-hoddie4.webp"
import menpagehoddie5 from "../assets/mensPage/hoddies/men-page-hoddie5.webp"
import menpagetshirt1 from "../assets/mensPage/tshirts/men-page-tshirt1.avif"
import menpagetshirt2 from "../assets/mensPage/tshirts/men-page-tshirt2.avif"
import menpagetshirt3 from "../assets/mensPage/tshirts/men-page-tshirt3.avif"
import menpagetshirt4 from "../assets/mensPage/tshirts/men-page-tshirt4.avif"
import menpagetshirt5 from "../assets/mensPage/tshirts/men-page-tshirt5.avif"

export const menspagesData = [
  // Casual Shirts
  {
    id: 1011,
    name: "Mufti",
    description: "Men's Blue Printed Casual Shirt",
    detailedDescription: "A stylish blue printed casual shirt from Mufti, perfect for a relaxed day out. Made from comfortable cotton fabric with a modern fit.",
    price: 800,
    image: menpagecasual1,
    category: "casualshirt",
    offers: true,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.2,
    totalRatings: 125,
    customerReviews: [
      { id: 1, user: "Amit S.", rating: 5, review: "Great shirt, comfortable and stylish. The print is really nice." },
      { id: 2, user: "Priya R.", rating: 4, review: "Good quality for the price. Fits well, but the color is slightly darker than expected." },
      { id: 3, user: "Rahul K.", rating: 4, review: "Decent shirt, fabric is soft. Would recommend sizing up if you prefer a looser fit." },
    ],
    search_keywords: ["mufti", "men's shirt", "men shirt", "casual shirt", "printed shirt", "blue shirt", "cotton shirt", "half sleeve shirt", "stylish shirt", "menswear", "top", "shirts"],
  },
  {
    id: 1012,
    name: "Roadster",
    description: "Men's Cotton Checked Casual Shirt",
    detailedDescription: "Classic cotton checked casual shirt from Roadster, ideal for everyday wear. Features a soft fabric and a comfortable regular fit.",
    price: 400,
    image: menpagecasual2,
    category: "casualshirt",
    offers: false,
    sizes: ["M", "L", "XL", "XXL"],
    averageRating: 3.9,
    totalRatings: 98,
    customerReviews: [
      { id: 1, user: "Sameer V.", rating: 3, review: "The checks are a bit too loud for my taste, but the shirt is comfortable." },
      { id: 2, user: "Divya N.", rating: 4, review: "Got this for my husband, he likes it. Good for casual outings." },
      { id: 3, user: "Kiran P.", rating: 4, review: "Decent shirt, fabric is soft. Would recommend sizing up if you prefer a looser fit." },
    ],
    search_keywords: ["roadster", "men's shirt", "men shirt", "casual shirt", "checked shirt", "cotton shirt", "regular fit shirt", "everyday shirt", "plaid shirt", "half sleeve shirt", "menswear", "top", "shirts"],
  },
  {
    id: 1013,
    name: "Highlander",
    description: "Slim Fit Striped Casual Shirt",
    detailedDescription: "A modern slim fit striped casual shirt by Highlander. Perfect for a smart casual look, made with a blend of cotton and linen for breathability.",
    price: 900,
    image: menpagecasual3,
    category: "casualshirt",
    offers: true,
    sizes: ["S", "M", "L"],
    averageRating: 4.5,
    totalRatings: 150,
    customerReviews: [
      { id: 1, user: "Vikram G.", rating: 5, review: "Love the fit and the stripes. Looks great with jeans." },
      { id: 2, user: "Anjali M.", rating: 5, review: "Bought this for my brother, he really likes the slim fit." },
      { id: 3, user: "Harish S.", rating: 4, review: "Stylish shirt, but it's a true slim fit, so order accordingly." },
    ],
    search_keywords: ["highlander", "men's shirt", "men shirt", "casual shirt", "slim fit shirt", "striped shirt", "cotton linen shirt", "smart casual", "modern shirt", "menswear", "top", "shirts"],
  },
  {
    id: 1014,
    name: "U.S. Polo Assn.",
    description: "Classic Fit Denim Casual Shirt",
    detailedDescription: "A timeless classic fit denim casual shirt from U.S. Polo Assn. Durable and versatile, perfect for layering or wearing on its own.",
    price: 1200,
    image: menpagecasual4,
    category: "casualshirt",
    offers: false,
    sizes: ["M", "L", "XL", "XXL"],
    averageRating: 4.3,
    totalRatings: 80,
    customerReviews: [
      { id: 1, user: "Rajesh K.", rating: 4, review: "Solid denim shirt. A bit heavy but good quality." },
      { id: 2, user: "Shweta L.", rating: 5, review: "My husband wears this all the time. Very classic." },
      { id: 3, user: "Prakash D.", rating: 4, review: "Good value, the denim is soft after a few washes." },
    ],
    search_keywords: ["us polo assn", "us polo", "men's shirt", "men shirt", "casual shirt", "denim shirt", "classic fit shirt", "durable shirt", "versatile shirt", "menswear", "top", "shirts"],
  },
  {
    id: 1015,
    name: "Dennis Lingo",
    description: "Mandarin Collar Solid Casual Shirt",
    detailedDescription: "Trendy mandarin collar solid casual shirt from Dennis Lingo. Adds a touch of modern sophistication to your casual wardrobe. Made from comfortable cotton.",
    price: 500,
    image: menpagecasual5,
    category: "casualshirt",
    offers: true,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.0,
    totalRatings: 110,
    customerReviews: [
      { id: 1, user: "Arjun B.", rating: 4, review: "Love the mandarin collar, it's very stylish." },
      { id: 2, user: "Meera C.", rating: 3, review: "Fabric is a bit thin, but good for summer." },
      { id: 3, user: "Gaurav H.", rating: 4, review: "Good for the price, fits well." },
    ],
    search_keywords: ["dennis lingo", "men's shirt", "men shirt", "casual shirt", "mandarin collar shirt", "solid shirt", "trendy shirt", "cotton shirt", "chinese collar shirt", "menswear", "top", "shirts"],
  },



  // Formal Shirts
  {
    id: 1016,
    name: "Raymond",
    description: "Men's Slim Fit Formal Shirt in White",
    detailedDescription: "A crisp white slim fit formal shirt from Raymond, perfect for professional settings. Made with premium fabric for a refined look and comfortable feel.",
    price: 350,
    image: menpageformal1,
    category: "formalshirt",
    offers: true,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.6,
    totalRatings: 200,
    customerReviews: [
      { id: 1, user: "Suresh R.", rating: 5, review: "Excellent quality and fit. A must-have white shirt." },
      { id: 2, user: "Deepa S.", rating: 5, review: "My husband looks very sharp in this shirt. Highly recommend." },
      { id: 3, user: "Ashok M.", rating: 4, review: "Good formal shirt, but requires regular ironing." },
      { id: 4, user: "Pooja V.", rating: 4, review: "Classic white shirt, good for office wear." },
    ],
    search_keywords: ["raymond", "men's shirt", "men shirt", "formal shirt", "white shirt", "slim fit shirt", "professional shirt", "premium fabric shirt", "office wear", "menswear", "top", "shirts"],
  },
  {
    id: 1017,
    name: "Van Heusen",
    description: "Cotton Blend Sky Blue Formal Shirt",
    detailedDescription: "A versatile cotton blend sky blue formal shirt from Van Heusen, suitable for both office and semi-formal occasions. Features a comfortable fit and wrinkle resistance.",
    price: 600,
    image: menpageformal2,
    category: "formalshirt",
    offers: false,
    sizes: ["M", "L", "XL", "XXL"],
    averageRating: 4.4,
    totalRatings: 180,
    customerReviews: [
      { id: 1, user: "Ravi K.", rating: 4, review: "Comfortable and looks good. The color is very pleasant." },
      { id: 2, user: "Anita D.", rating: 5, review: "Perfect for office, my husband wears it often." },
      { id: 3, user: "Vivek G.", rating: 4, review: "Good shirt, holds up well after washes." },
    ],
    search_keywords: ["van heusen", "men's shirt", "men shirt", "formal shirt", "sky blue shirt", "cotton blend shirt", "wrinkle resistant shirt", "office shirt", "semi-formal shirt", "menswear", "top", "shirts"],
  },
  {
    id: 1018,
    name: "Arrow",
    description: "Men's Striped Regular Fit Shirt",
    detailedDescription: "A classic striped regular fit formal shirt from Arrow, offering a sophisticated look for business meetings or formal events. Made with high-quality fabric for durability.",
    price: 1300,
    image: menpageformal3,
    category: "formalshirt",
    offers: true,
    sizes: ["S", "M", "L", "XL", "XXL"],
    averageRating: 4.7,
    totalRatings: 160,
    customerReviews: [
      { id: 1, user: "Gautam P.", rating: 5, review: "Excellent shirt, great fabric and perfect fit." },
      { id: 2, user: "Nisha R.", rating: 5, review: "Arrow never disappoints. This shirt is top-notch." },
      { id: 3, user: "Siddharth B.", rating: 4, review: "A bit pricey but worth it for the quality." },
    ],
    search_keywords: ["arrow", "men's shirt", "men shirt", "formal shirt", "striped shirt", "regular fit shirt", "business shirt", "durable shirt", "sophisticated shirt", "menswear", "top", "shirts"],
  },
  {
    id: 1019,
    name: "Peter England",
    description: "Plain Sky Blue Classic Formal Shirt",
    detailedDescription: "A timeless plain sky blue classic formal shirt from Peter England. A wardrobe essential for any gentleman, offering comfort and style for daily office wear.",
    price: 200,
    image: menpageformal4,
    category: "formalshirt",
    offers: true,
    sizes: ["M", "L", "XL"],
    averageRating: 4.1,
    totalRatings: 190,
    customerReviews: [
      { id: 1, user: "Kunal S.", rating: 4, review: "Good shirt for the price. The color is nice." },
      { id: 2, user: "Priyanka A.", rating: 3, review: "Decent, but the fabric feels a little thin." },
      { id: 3, user: "Rohit D.", rating: 4, review: "Satisfied with the purchase, good for daily use." },
    ],
    search_keywords: ["peter england", "men's shirt", "men shirt", "formal shirt", "plain shirt", "sky blue shirt", "classic shirt", "wardrobe essential", "daily office wear", "menswear", "top", "shirts"],
  },
  {
    id: 1020,
    name: "Louis Philippe",
    description: "Textured Slim Fit Formal Shirt",
    detailedDescription: "A sophisticated textured slim fit formal shirt from Louis Philippe. Perfect for adding a subtle detail to your formal attire, crafted with attention to detail.",
    price: 450,
    image: menpageformal5,
    category: "formalshirt",
    offers: false,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.5,
    totalRatings: 140,
    customerReviews: [
      { id: 1, user: "Varun N.", rating: 5, review: "The texture is subtle and elegant. Fits perfectly." },
      { id: 2, user: "Neha C.", rating: 4, review: "Great shirt for formal occasions. Looks premium." },
      { id: 3, user: 3, user: "Ajay G.", rating: 4, review: "Good quality, though the slim fit is quite snug." },
    ],
    search_keywords: ["louis philippe", "men's shirt", "men shirt", "formal shirt", "textured shirt", "slim fit shirt", "sophisticated shirt", "formal attire", "premium shirt", "menswear", "top", "shirts"],
  },



  // Traditional Wear
  {
    id: 1021,
    name: "Manyavar",
    description: "Embroidered Silk Kurta for Men",
    detailedDescription: "An exquisite embroidered silk kurta from Manyavar, ideal for weddings and festive occasions. Features intricate embroidery and luxurious silk fabric for a grand look.",
    price: 1800,
    image: menpagetradition1,
    category: "traditional",
    offers: true,
    sizes: ["M", "L", "XL"],
    averageRating: 4.8,
    totalRatings: 75,
    customerReviews: [
      { id: 1, user: "Sanjay R.", rating: 5, review: "Stunning kurta! The embroidery is beautiful." },
      { id: 2, user: "Meena K.", rating: 5, review: "Bought for my son's wedding, he looked fantastic." },
      { id: 3, user: "Preeti D.", rating: 4, review: "A bit heavy due to the silk, but very elegant." },
    ],
    search_keywords: ["manyavar", "men's traditional wear", "mens ethnic wear", "kurta", "kurta for men", "embroidered kurta", "silk kurta", "wedding wear", "festive wear", "indian wear", "grand look", "traditional clothing"],
  },
  {
    id: 1022,
    name: "FabIndia",
    description: "Cotton Printed Ethnic Wear",
    detailedDescription: "Comfortable cotton printed ethnic wear from FabIndia, ideal for casual festive wear or cultural events. Features traditional prints and breathable fabric.",
    price: 1200,
    image: menpagetradition2,
    category: "traditional",
    offers: false,
    sizes: ["M", "L", "XL", "XXL"],
    averageRating: 4.3,
    totalRatings: 60,
    customerReviews: [
      { id: 1, user: "Ritu S.", rating: 4, review: "Nice everyday ethnic wear. Very comfortable." },
      { id: 2, user: "Alok V.", rating: 4, review: "Good for pujas and small family gatherings." },
      { id: 3, user: "Deepak G.", rating: 3, review: "Print is nice, but the fabric could be softer." },
    ],
    search_keywords: ["fabindia", "men's traditional wear", "mens ethnic wear", "cotton ethnic wear", "printed ethnic wear", "casual festive wear", "cultural wear", "traditional prints", "kurta", "menswear", "indian wear", "traditional clothing"],
  },
  {
    id: 1023,
    name: "Sojanya",
    description: "Designer Festive Kurta Set",
    detailedDescription: "A stylish designer festive kurta set from Sojanya, perfect for celebrations. Includes a well-designed kurta and matching bottoms for a complete look.",
    price: 1000,
    image: menpagetradition3,
    category: "traditional",
    offers: true,
    sizes: ["L", "XL"],
    averageRating: 4.6,
    totalRatings: 55,
    customerReviews: [
      { id: 1, user: "Prakash L.", rating: 5, review: "Very elegant and festive. Got many compliments." },
      { id: 2, user: "Sneha M.", rating: 5, review: "The set is complete and looks very good." },
      { id: 3, user: "Aditya R.", rating: 4, review: "Good for the price, the fit is decent." },
    ],
    search_keywords: ["sojanya", "men's traditional wear", "mens ethnic wear", "kurta set", "designer kurta", "festive kurta", "celebration wear", "matching bottoms", "indian wear", "traditional clothing"],
  },
  {
    id: 1024,
    name: "Indus Route",
    description: "Pathani Suit in Solid Color",
    detailedDescription: "A classic Pathani suit in a solid color from Indus Route, offering a regal and traditional look. Made from comfortable fabric, suitable for various occasions.",
    price: 990,
    image: menpagetradition4,
    category: "traditional",
    offers: false,
    sizes: ["M", "L", "XL"],
    averageRating: 4.2,
    totalRatings: 40,
    customerReviews: [
      { id: 1, user: "Jitendra B.", rating: 4, review: "Looks very traditional and smart. Comfortable to wear." },
      { id: 2, user: "Geeta P.", rating: 4, review: "Bought for a family function, happy with the purchase." },
      { id: 3, user: "Kunal H.", rating: 3, review: "Good, but I wish there were more color options." },
    ],
    search_keywords: ["indus route", "men's traditional wear", "mens ethnic wear", "pathani suit", "solid color suit", "regal look", "traditional look", "kurta pajama", "menswear", "indian wear", "traditional clothing"],
  },
  {
    id: 1025,
    name: "BIBA Men",
    description: "Traditional Cotton Long Kurta",
    detailedDescription: "A comfortable and stylish traditional cotton long kurta from BIBA Men, perfect for everyday ethnic wear or festive gatherings. Soft fabric and classic design.",
    price: 1090,
    image: menpagetradition5,
    category: "traditional",
    offers: true,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.5,
    totalRatings: 65,
    customerReviews: [
      { id: 1, user: "Ramesh C.", rating: 5, review: "Very comfortable and good quality cotton kurta." },
      { id: 2, user: "Shalini K.", rating: 4, review: "Nice for daily wear, the color is vibrant." },
      { id: 3, user: "Pranav S.", rating: 4, review: "Good traditional option, fits well." },
    ],
    search_keywords: ["biba men", "men's traditional wear", "mens ethnic wear", "long kurta", "cotton kurta", "everyday ethnic wear", "festive kurta", "classic design", "menswear", "indian wear", "traditional clothing"],
  },


  // Hoodies
  {
    id: 1026,
    name: "H&M",
    description: "Oversized Fleece Hoodie in Olive",
    detailedDescription: "A cozy oversized fleece hoodie in olive from H&M, perfect for a relaxed and stylish look. Made from soft fleece fabric for maximum comfort.",
    price: 600,
    image: menpagehoddie1,
    category: "hoddie",
    offers: false,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.3,
    totalRatings: 150,
    customerReviews: [
      { id: 1, user: "Ankit R.", rating: 5, review: "Super comfortable and stylish. Love the oversized fit." },
      { id: 2, user: "Disha P.", rating: 4, review: "Great for chilly evenings. The fleece is very soft." },
      { id: 3, user: "Rohit M.", rating: 4, review: "Good hoodie for the price, but the color is a bit muted." },
    ],
    search_keywords: ["h&m", "men's hoodie", "mens hoodie", "oversized hoodie", "fleece hoodie", "olive hoodie", "cozy hoodie", "relaxed fit", "sweatshirt", "hooded sweatshirt", "menswear", "jacket", "winter wear", "outerwear"],
  },
  {
    id: 1027,
    name: "Puma",
    description: "Classic Zip-Up Hoodie for Training",
    detailedDescription: "A classic zip-up hoodie from Puma, ideal for training or everyday casual wear. Features a comfortable fit and Puma's signature style.",
    price: 750,
    image: menpagehoddie2,
    category: "hoddie",
    offers: true,
    sizes: ["M", "L", "XL", "XXL"],
    averageRating: 4.5,
    totalRatings: 180,
    customerReviews: [
      { id: 1, user: "Suresh B.", rating: 5, review: "Perfect for workouts and casual outings. Good quality zip." },
      { id: 2, user: "Kavya N.", rating: 4, review: "My brother loves this hoodie. Very practical." },
      { id: 3, user: "Pratik D.", rating: 4, review: "Comfortable and durable. Puma never disappoints." },
    ],
    search_keywords: ["puma", "men's hoodie", "mens hoodie", "zip-up hoodie", "training hoodie", "athletic hoodie", "casual hoodie", "sports hoodie", "sweatshirt", "hooded sweatshirt", "menswear", "jacket", "gym wear", "outerwear"],
  },
  {
    id: 1028,
    name: "Adidas",
    description: "Men's Logo Printed Hoodie",
    detailedDescription: "A stylish men's logo printed hoodie from Adidas, featuring the iconic Adidas logo. Great for athletic wear or a comfortable casual look.",
    price: 850,
    image: menpagehoddie3,
    category: "hoddie",
    offers: false,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.6,
    totalRatings: 200,
    customerReviews: [
      { id: 1, user: "Aryan G.", rating: 5, review: "Classic Adidas hoodie. Very comfortable and looks great." },
      { id: 2, user: "Priya V.", rating: 5, review: "Good quality, the logo is well printed." },
      { id: 3, user: "Karan S.", rating: 4, review: "A bit expensive, but the brand value is there." },
    ],
    search_keywords: ["adidas", "men's hoodie", "mens hoodie", "logo hoodie", "printed hoodie", "athletic wear", "casual hoodie", "iconic logo", "sweatshirt", "hooded sweatshirt", "menswear", "jacket", "sports wear", "outerwear"],
  },
  {
    id: 1029,
    name: "Nike",
    description: "Sportswear Club Fleece Hoodie",
    detailedDescription: "The iconic Nike Sportswear Club Fleece Hoodie, known for its ultimate comfort and versatile style. A wardrobe staple for any casual or sporty look.",
    price: 990,
    image: menpagehoddie4,
    category: "hoddie",
    offers: true,
    sizes: ["S", "M", "L", "XL", "XXL"],
    averageRating: 4.7,
    totalRatings: 250,
    customerReviews: [
      { id: 1, user: "Rahul J.", rating: 5, review: "The most comfortable hoodie I own. Highly recommend." },
      { id: 2, user: "Shreya T.", rating: 5, review: "Bought for my son, he wears it everywhere. Excellent quality." },
      { id: 3, user: "Vikas M.", rating: 4, review: "Worth the price, very durable and warm." },
    ],
    search_keywords: ["nike", "men's hoodie", "mens hoodie", "sportswear hoodie", "fleece hoodie", "club fleece", "comfortable hoodie", "sporty look", "casual hoodie", "sweatshirt", "hooded sweatshirt", "menswear", "jacket", "outerwear"],
  },
  {
    id: 1030,
    name: "Superdry",
    description: "Vintage Graphic Hoodie in Black",
    detailedDescription: "A trendy vintage graphic hoodie in black from Superdry, featuring unique graphics for a distinct style. Made with soft fabric for a comfortable feel.",
    price: 1200,
    image: menpagehoddie5,
    category: "hoddie",
    offers: false,
    sizes: ["M", "L", "XL"],
    averageRating: 4.4,
    totalRatings: 100,
    customerReviews: [
      { id: 1, user: "Sameer N.", rating: 4, review: "Stylish hoodie, the graphic print is cool." },
      { id: 2, user: "Divya C.", rating: 4, review: "Good fit and comfortable, but a bit pricey." },
      { id: 3, user: "Arjun P.", rating: 5, review: "Love Superdry products. This hoodie lives up to expectations." },
    ],
    search_keywords: ["superdry", "men's hoodie", "mens hoodie", "vintage hoodie", "graphic hoodie", "black hoodie", "trendy hoodie", "distinct style", "sweatshirt", "hooded sweatshirt", "menswear", "jacket", "outerwear"],
  },



  // T-Shirts
  {
    id: 1031,
    name: "Jack & Jones",
    description: "Slim Fit Cotton Graphic Tee",
    detailedDescription: "A fashionable slim fit cotton graphic tee from Jack & Jones, perfect for adding a stylish touch to your casual outfits. Features a cool graphic print.",
    price: 300,
    image: menpagetshirt1,
    category: "tshirt",
    offers: true,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.1,
    totalRatings: 220,
    customerReviews: [
      { id: 1, user: "Amit K.", rating: 4, review: "Good graphic tee, comfortable for everyday wear." },
      { id: 2, user: "Priya L.", rating: 3, review: "The fit is good, but the fabric is a bit thin." },
      { id: 3, user: "Rahul G.", rating: 4, review: "Great value for money, stylish design." },
    ],
    search_keywords: ["jack & jones", "men's t-shirt", "mens tee", "tshirt", "graphic tee", "slim fit tee", "cotton tee", "casual t-shirt", "printed t-shirt", "half sleeve t-shirt", "menswear", "top", "shirts"],
  },
  {
    id: 1032,
    name: "Levi's",
    description: "Classic Red Crew Neck T-Shirt",
    detailedDescription: "A timeless classic red crew neck T-shirt from Levi's, a wardrobe essential for casual styling. Made from soft cotton for ultimate comfort.",
    price: 250,
    image: menpagetshirt2,
    category: "tshirt",
    offers: false,
    sizes: ["M", "L", "XL", "XXL"],
    averageRating: 4.5,
    totalRatings: 280,
    customerReviews: [
      { id: 1, user: "Ravi S.", rating: 5, review: "Perfect red t-shirt, great quality and comfortable." },
      { id: 2, user: "Meera D.", rating: 4, review: "Good basic tee, washes well." },
      { id: 3, user: "Sanjay N.", rating: 5, review: "Levi's quality is always good. Happy with the purchase." },
    ],
    search_keywords: ["levi's", "men's t-shirt", "mens tee", "tshirt", "red t-shirt", "crew neck tee", "classic t-shirt", "cotton t-shirt", "casual t-shirt", "wardrobe essential", "half sleeve t-shirt", "menswear", "top", "shirts"],
  },
  {
    id: 1033,
    name: "Bewakoof",
    description: "Printed Half Sleeve Tee",
    detailedDescription: "A fun and quirky printed half sleeve tee from Bewakoof, perfect for expressing your unique style. Features creative prints and comfortable fabric.",
    price: 400,
    image: menpagetshirt3,
    category: "tshirt",
    offers: true,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.0,
    totalRatings: 190,
    customerReviews: [
      { id: 1, user: "Arjun K.", rating: 4, review: "Love the print and the comfortable fit." },
      { id: 2, user: "Neha P.", rating: 3, review: "Fabric is a bit thin, but good for summer." },
      { id: 3, user: "Gaurav H.", rating: 4, review: "Unique designs, great for a relaxed look." },
    ],
    search_keywords: ["bewakoof", "men's t-shirt", "mens tee", "tshirt", "printed tee", "half sleeve tee", "quirky t-shirt", "funky t-shirt", "casual t-shirt", "unique style", "menswear", "top", "shirts"],
  },
  {
    id: 1034,
    name: "Zara",
    description: "Minimalist White T-Shirt",
    detailedDescription: "A clean and versatile minimalist white T-shirt from Zara, a staple for any wardrobe. Perfect for layering or wearing on its own for a crisp look.",
    price: 550,
    image: menpagetshirt4,
    category: "tshirt",
    offers: false,
    sizes: ["S", "M", "L"],
    averageRating: 4.3,
    totalRatings: 160,
    customerReviews: [
      { id: 1, user: "Vikas T.", rating: 5, review: "Perfect basic white tee. Good quality." },
      { id: 2, user: "Sneha B.", rating: 4, review: "A bit expensive for a plain white tee, but it's Zara quality." },
      { id: 3, user: "Punit C.", rating: 4, review: "Comfortable and versatile. A must-have." },
    ],
    search_keywords: ["zara", "men's t-shirt", "mens tee", "tshirt", "white t-shirt", "minimalist tee", "basic tee", "wardrobe staple", "clean look", "casual t-shirt", "half sleeve t-shirt", "menswear", "top", "shirts"],
  },
  {
    id: 1035,
    name: "HRX",
    description: "Athletic Fit Sports T-Shirt",
    detailedDescription: "Athletic Fit Sports T-Shirt, designed for active individuals. Features moisture-wicking fabric for comfort during workouts.",
    price: 650,
    image: menpagetshirt5,
    category: "tshirt",
    offers: true,
    sizes: ["M", "L", "XL", "XXL"],
    averageRating: 4.6,
    totalRatings: 130,
    customerReviews: [
      { id: 1, user: "Rohit D.", rating: 5, review: "Great for gym and running. Very breathable." },
      { id: 2, user: "Pooja G.", rating: 4, review: "Good sports tee, the fit is snug but comfortable." },
      { id: 3, user: "Akash M.", rating: 4, review: "Effective moisture-wicking. Happy with the performance." },
    ],
    search_keywords: ["hrx", "men's t-shirt", "mens tee", "tshirt", "athletic tee", "sports t-shirt", "moisture-wicking tee", "workout shirt", "gym wear", "running shirt", "performance tee", "half sleeve t-shirt", "menswear", "top", "shirts"],
  },
];