export const Searchkeywords = [
  // Men's Wear Keywords
  "hrx", "men's t-shirt", "mens tee", "tshirt", "athletic tee", "sports t-shirt",
  "moisture-wicking tee", "workout shirt", "gym wear", "running shirt",
  "performance tee", "half sleeve t-shirt", "menswear", "top", "shirts",
  "mufti", "men's shirt", "men shirt", "casual shirt", "printed shirt",
  "blue shirt", "cotton shirt", "stylish shirt", "roadster", "checked shirt",
  "regular fit shirt", "everyday shirt", "plaid shirt", "highlander",
  "slim fit shirt", "striped shirt", "cotton linen shirt", "smart casual",
  "modern shirt", "us polo assn", "us polo", "denim shirt", "classic fit shirt",
  "durable shirt", "versatile shirt", "dennis lingo", "mandarin collar shirt",
  "solid shirt", "trendy shirt", "chinese collar shirt", "raymond", "formal shirt",
  "white shirt", "professional shirt", "premium fabric shirt", "office wear",
  "van heusen", "cotton blend shirt", "sky blue shirt", "wrinkle resistant shirt",
  "semi-formal shirt", "arrow", "business shirt", "sophisticated shirt",
  "peter england", "plain shirt", "classic shirt", "wardrobe essential",
  "daily office wear", "louis philippe", "textured shirt", "formal attire",
  "premium shirt", "manyavar", "men's traditional wear", "mens ethnic wear",
  "kurta", "kurta for men", "embroidered kurta", "silk kurta", "wedding wear",
  "festive wear", "indian wear", "grand look", "traditional clothing", "fabindia",
  "cotton ethnic wear", "printed ethnic wear", "casual festive wear", "cultural wear",
  "traditional prints", "sojanya", "kurta set", "designer kurta", "festive kurta",
  "celebration wear", "matching bottoms", "indus route", "pathani suit",
  "solid color suit", "regal look", "traditional look", "kurta pajama",
  "biba men", "long kurta", "cotton kurta", "everyday ethnic wear", "classic design",
  "h&m", "men's hoodie", "mens hoodie", "oversized hoodie", "fleece hoodie",
  "olive hoodie", "cozy hoodie", "relaxed fit", "sweatshirt", "hooded sweatshirt",
  "jacket", "winter wear", "outerwear", "puma", "zip-up hoodie", "training hoodie",
  "athletic hoodie", "casual hoodie", "sports hoodie", "adidas", "logo hoodie",
  "printed hoodie", "athletic wear", "iconic logo", "nike", "sportswear hoodie",
  "club fleece", "comfortable hoodie", "sporty look", "superdry", "vintage hoodie",
  "graphic hoodie", "black hoodie", "distinct style", "jack & jones", "graphic tee",
  "slim fit tee", "cotton tee", "casual t-shirt", "printed t-shirt", "levi's",
  "red t-shirt", "crew neck tee", "bewakoof", "printed tee", "funky t-shirt",
  "quirky t-shirt", "unique style", "zara", "white t-shirt", "minimalist tee", "basic tee",
  "clean look",

  // Kids' Wear Keywords
  "bownbee", "kids traditional", "boys traditional", "ethnic wear boys",
  "kurta pajama set", "kurta for boys", "pajama for boys", "festive wear kids",
  "family gathering outfit", "indian wear kids", "boys ethnic", "kids ethnic",
  "tiber taber", "dhoti kurta set", "dhoti for boys", "festive dhoti",
  "wedding wear kids", "cultural event outfit", "biba kids", "girls traditional",
  "ethnic wear girls", "lehenga choli set", "printed lehenga", "girls lehenga",
  "choli for girls", "festive lehenga", "girls ethnic", "aarika",
  "traditional dress kids", "dupatta dress", "girls ethnic dress",
  "special event dress kids", "kids ethnic gown", "hopscotch", "sherwani suit",
  "embroidered sherwani", "formal traditional wear", "wedding sherwani kids",
  "boys sherwani", "kids ethnic suit", "mothercare", "kids hoodie", "baby hoodie",
  "cozy hoodie", "everyday hoodie", "kids sweatshirt", "toddler hoodie",
  "infant hoodie", "winter wear kids",

  // Women's Wear Keywords
  "silk route", "daily wear saree", "floral printed saree", "lightweight saree",
  "everyday saree", "office wear saree", "printed cotton saree", "womens saree",
  "casual saree", "ishin", "lightweight casual daily saree", "soft fabric saree",
  "humid weather saree", "affordable saree", "vishudh", "ethnic printed saree",
  "traditional print saree", "easy drape saree", "satrani", "cotton blend saree",
  "breathable saree", "easy movement saree", "anouk", "abstract print saree",
  "modern saree", "stylish saree", "kanchipuram weaves", "pattu saree",
  "pure silk saree", "traditional pattu", "grand celebration saree",
  "kanchipuram silk", "silk saree", "heirloom saree", "south indian saree",
  "bridal saree", "pothys", "woven silk saree", "traditional motifs saree",
  "womens bridal wear", "samudrika", "gold border saree", "designer silk saree",
  "luxurious saree", "grand occasion saree", "traditional silk saree",
  "womens festive saree", "silkalay", "pure zari saree", "rich pattu",
  "zari work saree", "grand festivities saree", "luxurious silk saree",
  "nalli", "heavy banarasi saree", "banarasi pattu", "timeless elegance saree",
  "traditional craftsmanship saree", "grand event saree", "womens traditional wear",
  "clovia", "nightwear", "night suit set", "cotton night suit", "soft nightwear",
  "comfortable nightwear", "breathable nightwear", "relaxed fit nightwear",
  "pajama set", "sleepwear", "womens night dress", "summer nightwear",
  "zivame", "lounge style dress", "night dress", "comfortable night dress",
  "loungewear", "casual nightwear", "enamor", "printed nightwear",
  "comfort fit nightwear", "skin-friendly nightwear", "womens night suit",
  "pajamas", "prettysecrets", "full sleeve pajama set", "cozy pajama set",
  "winter nightwear", "stylish nightwear", "comfortable pajama", "jockey",
  "breathable night dress", "lounge night dress", "comfortable sleepwear",
  "quality nightwear", "relaxed evenings nightwear", "and", "dress",
  "floral dress", "fit & flare dress", "semi-formal dress", "vibrant floral print",
  "summer dress", "womens dress", "party dress", "midi dress", "global desi",
  "ethnic maxi dress", "bohemian dress", "flowy dress", "stylish dress",
  "long dress", "timeless dress", "versatile dress", "formal dress",
  "cocktail dress", "little black dress", "biba", "day dress", "light dress",
  "breathable dress", "only", "layered dress", "ruffle dress", "midi dress",
  "trendy dress", "feminine dress", "casual events dress", "caprese", "handbag",
  "shoulder bag", "solid bag", "textured bag", "everyday bag", "chic bag",
  "spacious bag", "womens handbag", "casual bag", "lavie", "tote bag",
  "everyday tote", "stylish tote", "spacious tote", "trendy design bag",
  "baggit", "faux leather handbag", "elegant handbag", "ethical fashion bag",
  "sophisticated design bag", "vegan bag", "office bag", "hidesign",
  "genuine leather bag", "classic leather bag", "timeless bag",
  "superior craftsmanship bag", "durable bag", "investment bag", "luxury bag",
  "zouk", "handmade bag", "indian aesthetics bag", "modern functionality bag",
  "sustainable bag", "laptop bag", "work bag"
]