import womenpagesaree1 from "../assets/womensPage/dailywearSarees/women-page-saree1.avif"
import womenpagesaree2 from "../assets/womensPage/dailywearSarees/women-page-saree2.avif"
import womenpagesaree3 from "../assets/womensPage/dailywearSarees/women-page-saree3.avif"
import womenpagesaree4 from "../assets/womensPage/dailywearSarees/women-page-saree4.avif"
import womenpagesaree5 from "../assets/womensPage/dailywearSarees/women-page-saree5.avif"
import womenpagepattusaree1 from "../assets/womensPage/pattuSarees/women-page-pattusaree1.avif"
import womenpagepattusaree2 from "../assets/womensPage/pattuSarees/women-page-pattusaree2.avif"
import womenpagepattusaree3 from "../assets/womensPage/pattuSarees/women-page-pattusaree3.avif"
import womenpagepattusaree4 from "../assets/womensPage/pattuSarees/women-page-pattusaree4.avif"
import womenpagepattusaree5 from "../assets/womensPage/pattuSarees/women-page-pattusaree5.avif"
import womenpagenightwear1 from "../assets/womensPage/nightdresses/women-page-nightwear1.avif"
import womenpagenightwear2 from "../assets/womensPage/nightdresses/women-page-nightwear2.avif"
import womenpagenightwear3 from "../assets/womensPage/nightdresses/women-page-nightwear3.avif"
import womenpagenightwear4 from "../assets/womensPage/nightdresses/women-page-nightwear4.avif"
import womenpagenightwear5 from "../assets/womensPage/nightdresses/women-page-nightwear5.avif"
import womenpagedress1 from "../assets/womensPage/womendresses/women-page-dress1.avif"
import womenpagedress2 from "../assets/womensPage/womendresses/women-page-dress2.avif"
import womenpagedress3 from "../assets/womensPage/womendresses/women-page-dress3.avif"
import womenpagedress4 from "../assets/womensPage/womendresses/women-page-dress4.avif"
import womenpagedress5 from "../assets/womensPage/womendresses/women-page-dress5.avif"
import womenpagehandbag1 from "../assets/womensPage/handbags/women-page-handbag1.avif"
import womenpagehandbag2 from "../assets/womensPage/handbags/women-page-handbag2.avif"
import womenpagehandbag3 from "../assets/womensPage/handbags/women-page-handbag3.avif"
import womenpagehandbag4 from "../assets/womensPage/handbags/women-page-handbag4.avif"
import womenpagehandbag5 from "../assets/womensPage/handbags/women-page-handbag5.avif"



export const womenspagesData = [
  // Daily Wear Sarees
  {
    id: 2011,
    name: "Silk Route",
    description: "Floral Printed Cotton Saree",
    detailedDescription: "A beautiful floral printed cotton saree from Silk Route, perfect for comfortable daily wear. Lightweight and easy to drape, ideal for everyday elegance.",
    price: 850,
    image: womenpagesaree1,
    category: "dailywearsaree",
    offers: true,
    sizes: ["OneSize"],
    averageRating: 4.2,
    totalRatings: 150,
    customerReviews: [
      { id: 1, user: "Radha M.", rating: 5, review: "Lovely saree for daily use. Very comfortable and the print is pretty." },
      { id: 2, user: "Priya S.", rating: 4, review: "Good quality cotton, easy to manage. Slightly lighter color than expected." },
      { id: 3, user: "Anjali K.", rating: 4, review: "Affordable and stylish. Perfect for office wear." },
    ],
    search_keywords: ["silk route", "daily wear saree", "cotton saree", "floral printed saree", "lightweight saree", "everyday saree", "comfortable saree", "office wear saree", "printed cotton saree", "womens saree", "casual saree"],
  },
  {
    id: 2012,
    name: "Ishin",
    description: "Lightweight Casual Daily Saree",
    detailedDescription: "This lightweight casual daily saree from Ishin is designed for effortless elegance. Its soft fabric makes it perfect for long hours of wear.",
    price: 650,
    image: womenpagesaree2,
    category: "dailywearsaree",
    offers: false,
    sizes: ["OneSize"],
    averageRating: 3.9,
    totalRatings: 120,
    customerReviews: [
      { id: 1, user: "Meena R.", rating: 3, review: "It's okay for daily wear, but the fabric feels a bit synthetic." },
      { id: 2, user: "Sunita G.", rating: 4, review: "Very light and comfortable. Good for humid weather." },
      { id: 3, user: "Deepa N.", rating: 4, review: "Decent saree for the price. Happy with the purchase." },
    ],
    search_keywords: ["ishin", "daily wear saree", "casual saree", "lightweight saree", "soft fabric saree", "everyday saree", "comfortable saree", "humid weather saree", "womens saree", "affordable saree"],
  },
  {
    id: 2013,
    name: "Vishudh",
    description: "Ethnic Printed Daily Use Saree",
    detailedDescription: "An ethnically printed saree from Vishudh, ideal for daily use or casual outings. Features traditional prints on comfortable fabric for a graceful look.",
    price: 700,
    image: womenpagesaree3,
    category: "dailywearsaree",
    offers: true,
    sizes: ["OneSize"],
    averageRating: 4.0,
    totalRatings: 100,
    customerReviews: [
      { id: 1, user: "Kavita D.", rating: 4, review: "The print is lovely and the saree is easy to drape." },
      { id: 2, user: "Ritu S.", rating: 3, review: "Good for the price, but the material wrinkles easily." },
      { id: 3, user: "Poonam L.", rating: 4, review: "Comfortable daily wear saree. Very happy." },
    ],
    search_keywords: ["vishudh", "daily wear saree", "ethnic printed saree", "traditional print saree", "casual saree", "comfortable saree", "easy drape saree", "womens saree", "everyday saree"],
  },
  {
    id: 2014,
    name: "Satrani",
    description: "Comfort Cotton Blend Saree",
    detailedDescription: "Experience comfort with this cotton blend saree from Satrani. Perfect for long hours, offering breathability and ease of movement for daily activities.",
    price: 599,
    image: womenpagesaree4,
    category: "dailywearsaree",
    offers: true,
    sizes: ["OneSize"],
    averageRating: 4.3,
    totalRatings: 180,
    customerReviews: [
      { id: 1, user: "Alka V.", rating: 5, review: "Excellent quality for the price. Very comfortable for daily wear." },
      { id: 2, user: "Geeta H.", rating: 4, review: "Soft fabric and good drape. Worth buying." },
      { id: 3, user: "Sarita J.", rating: 4, review: "My go-to saree for everyday. Lightweight and easy to maintain." },
    ],
    search_keywords: ["satrani", "daily wear saree", "cotton blend saree", "comfortable saree", "breathable saree", "easy movement saree", "everyday saree", "lightweight saree", "womens saree", "affordable saree"],
  },
  {
    id: 2015,
    name: "Anouk",
    description: "Abstract Print Cotton Saree",
    detailedDescription: "A contemporary abstract print cotton saree from Anouk, adding a modern touch to your daily wear collection. Made from soft cotton, it's stylish and comfortable.",
    price: 900,
    image: womenpagesaree5,
    category: "dailywearsaree",
    offers: false,
    sizes: ["OneSize"],
    averageRating: 4.1,
    totalRatings: 90,
    customerReviews: [
      { id: 1, user: "Mona P.", rating: 4, review: "Unique print, I love it! Good for casual outings." },
      { id: 2, user: "Tina K.", rating: 3, review: "The print is nice, but the fabric is a little stiff." },
      { id: 3, user: "Rohan D.", rating: 4, review: "Bought for my wife, she likes the modern design." },
    ],
    search_keywords: ["anouk", "daily wear saree", "abstract print saree", "cotton saree", "modern saree", "stylish saree", "comfortable saree", "casual saree", "womens saree", "printed cotton saree"],
  },



  // Pattu Sarees
  {
    id: 2021,
    name: "Kanchipuram Weaves",
    description: "Traditional Pure Silk Pattu Saree",
    detailedDescription: "An exquisite traditional pure silk pattu saree from Kanchipuram Weaves, a masterpiece of weaving art. Perfect for weddings and grand celebrations.",
    price: 3500,
    image: womenpagepattusaree1,
    category: "pattusaree",
    offers: true,
    sizes: ["OneSize"],
    averageRating: 4.8,
    totalRatings: 70,
    customerReviews: [
      { id: 1, user: "Lakshmi R.", rating: 5, review: "Absolutely stunning saree. The silk is so rich and the weaving is intricate." },
      { id: 2, user: "Suresh P.", rating: 5, review: "Bought for my daughter's wedding. It's a true heirloom piece." },
      { id: 3, user: "Meena K.", rating: 4, review: "Beautiful, but very heavy to wear for long hours." },
    ],
    search_keywords: ["kanchipuram weaves", "pattu saree", "pure silk saree", "traditional pattu", "wedding saree", "grand celebration saree", "kanchipuram silk", "silk saree", "heirloom saree", "south indian saree", "bridal saree"],
  },
  {
    id: 2022,
    name: "Pothys",
    description: "Bridal Woven Silk Saree",
    detailedDescription: "A magnificent bridal woven silk saree from Pothys, designed to make your special day unforgettable. Features intricate weaving and rich traditional motifs.",
    price: 2800,
    image: womenpagepattusaree2,
    category: "pattusaree",
    offers: false,
    sizes: ["OneSize"],
    averageRating: 4.7,
    totalRatings: 60,
    customerReviews: [
      { id: 1, user: "Priya V.", rating: 5, review: "Gorgeous saree for my bridal trousseau. The craftsmanship is amazing." },
      { id: 2, user: "Ramya N.", rating: 4, review: "Very beautiful, but the color was slightly different than shown online." },
      { id: 3, user: "Anand M.", rating: 5, review: "A classic Pothys saree. Excellent value." },
    ],
    search_keywords: ["pothys", "pattu saree", "bridal saree", "woven silk saree", "wedding saree", "traditional motifs saree", "silk saree", "womens bridal wear", "festive saree"],
  },
  {
    id: 2023,
    name: "Samudrika",
    description: "Gold Border Designer Silk Saree",
    detailedDescription: "A luxurious gold border designer silk saree from Samudrika, perfect for adding a touch of grandeur to any occasion. The rich border enhances its traditional appeal.",
    price: 3900,
    image: womenpagepattusaree3,
    category: "pattusaree",
    offers: true,
    sizes: ["OneSize"],
    averageRating: 4.6,
    totalRatings: 55,
    customerReviews: [
      { id: 1, user: "Shalini G.", rating: 5, review: "The gold border is exquisite. Looks very regal." },
      { id: 2, user: "Vivek T.", rating: 4, review: "A bit expensive, but the quality of silk is undeniable." },
      { id: 3, user: "Kavya P.", rating: 4, review: "Received many compliments wearing this saree." },
    ],
    search_keywords: ["samudrika", "pattu saree", "gold border saree", "designer silk saree", "luxurious saree", "grand occasion saree", "traditional silk saree", "womens festive saree", "silk saree"],
  },
  {
    id: 2024,
    name: "Silkalay",
    description: "Pure Zari Rich Pattu Saree",
    detailedDescription: "Drape yourself in luxury with this pure zari rich pattu saree from Silkalay. Known for its rich zari work and traditional appeal, ideal for grand festivities.",
    price: 4200,
    image: womenpagepattusaree4,
    category: "pattusaree",
    offers: false,
    sizes: ["OneSize"],
    averageRating: 4.9,
    totalRatings: 45,
    customerReviews: [
      { id: 1, user: "Divya R.", rating: 5, review: "The zari work is incredibly detailed. A stunning saree." },
      { id: 2, user: "Rajesh S.", rating: 5, review: "Bought for my mother, she loved the richness of the saree." },
      { id: 3, user: "Poonam H.", rating: 5, review: "Feels very luxurious. Worth every penny." },
    ],
    search_keywords: ["silkalay", "pattu saree", "pure zari saree", "rich pattu", "zari work saree", "traditional saree", "grand festivities saree", "luxurious silk saree", "wedding saree", "festive saree"],
  },
  {
    id: 2025,
    name: "Nalli",
    description: "Heavy Banarasi Pattu Saree",
    detailedDescription: "A magnificent heavy Banarasi pattu saree from Nalli, embodying timeless elegance and traditional craftsmanship. Perfect for making a statement at any grand event.",
    price: 5000,
    image: womenpagepattusaree5,
    category: "pattusaree",
    offers: true,
    sizes: ["OneSize"],
    averageRating: 4.8,
    totalRatings: 50,
    customerReviews: [
      { id: 1, user: "Geetha M.", rating: 5, review: "Nalli's quality is always exceptional. This Banarasi is stunning." },
      { id: 2, user: "Siddharth J.", rating: 4, review: "Very grand and heavy. Best for specific occasions." },
      { id: 3, user: "Swati L.", rating: 5, review: "An investment piece. The weaving is just incredible." },
    ],
    search_keywords: ["nalli", "pattu saree", "heavy banarasi saree", "banarasi pattu", "timeless elegance saree", "traditional craftsmanship saree", "grand event saree", "silk saree", "wedding saree", "festive saree", "womens traditional wear"],
  },



  // Nightwear
  {
    id: 2031,
    name: "Clovia",
    description: "Soft Cotton Night Suit Set",
    detailedDescription: "A super soft cotton night suit set from Clovia, designed for ultimate comfort and a good night's sleep. Breathable fabric and relaxed fit.",
    price: 850,
    image: womenpagenightwear1,
    category: "nightwear",
    offers: true,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.3,
    totalRatings: 110,
    customerReviews: [
      { id: 1, user: "Disha R.", rating: 5, review: "Very comfortable and stylish night suit. Love the soft fabric." },
      { id: 2, user: "Kiran P.", rating: 4, review: "Good for summer nights. The fit is perfect." },
      { id: 3, user: "Anjali S.", rating: 4, review: "Clovia never disappoints. Decent quality for the price." },
    ],
    search_keywords: ["clovia", "nightwear", "night suit set", "cotton night suit", "soft nightwear", "comfortable nightwear", "breathable nightwear", "relaxed fit nightwear", "pajama set", "sleepwear", "womens night dress", "summer nightwear"],
  },
  {
    id: 2032,
    name: "Zivame",
    description: "Lounge Style Night Dress",
    detailedDescription: "A chic lounge style night dress from Zivame, perfect for relaxing at home. Made from breathable fabric for comfort and a relaxed fit.",
    price: 780,
    image: womenpagenightwear2,
    category: "nightwear",
    offers: false,
    sizes: ["M", "L", "XL", "XXL"],
    averageRating: 4.1,
    totalRatings: 95,
    customerReviews: [
      { id: 1, user: "Ria M.", rating: 4, review: "Comfortable for lounging around the house. Good material." },
      { id: 2, user: "Pooja V.", rating: 3, review: "The style is nice, but it runs a little small." },
      { id: 3, user: "Sunita C.", rating: 4, review: "Good for a casual night dress. Easy to wash." },
    ],
    search_keywords: ["zivame", "nightwear", "lounge style dress", "night dress", "comfortable night dress", "breathable nightwear", "relaxed fit nightwear", "loungewear", "womens night dress", "casual nightwear"],
  },
  {
    id: 2033,
    name: "Enamor",
    description: "Comfort Fit Printed Nightwear",
    detailedDescription: "Enjoy a comfortable sleep in this printed nightwear from Enamor. Designed for a relaxed fit and made with soft, skin-friendly fabric.",
    price: 990,
    image: womenpagenightwear3,
    category: "nightwear",
    offers: true,
    sizes: ["S", "M", "L"],
    averageRating: 4.5,
    totalRatings: 80,
    customerReviews: [
      { id: 1, user: "Seema A.", rating: 5, review: "Excellent quality and very comfortable. The print is cute." },
      { id: 2, user: "Divya N.", rating: 4, review: "Soft fabric, perfect for a good night's sleep." },
      { id: 3, user: "Kavita D.", rating: 4, review: "A bit pricey but the comfort level is worth it." },
    ],
    search_keywords: ["enamor", "nightwear", "printed nightwear", "comfort fit nightwear", "soft nightwear", "skin-friendly nightwear", "relaxed fit nightwear", "sleepwear", "womens night suit", "pajamas"],
  },
  {
    id: 2034,
    name: "PrettySecrets",
    description: "Full Sleeve Pajama Set",
    detailedDescription: "A cozy full sleeve pajama set from PrettySecrets, ideal for cooler nights. Stylish and comfortable, made from soft fabric for a good night's rest.",
    price: 1100,
    image: womenpagenightwear4,
    category: "nightwear",
    offers: false,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.4,
    totalRatings: 70,
    customerReviews: [
      { id: 1, user: "Shruti L.", rating: 5, review: "Very warm and cozy. Perfect for winter nights." },
      { id: 2, user: "Akash R.", rating: 4, review: "Bought for my wife, she says it's very comfortable." },
      { id: 3, user: "Priya S.", rating: 4, review: "Good quality material, holds up well after washing." },
    ],
    search_keywords: ["prettysecrets", "nightwear", "full sleeve pajama set", "cozy pajama set", "winter nightwear", "stylish nightwear", "comfortable pajama", "womens night suit", "sleepwear"],
  },
  {
    id: 2035,
    name: "Jockey",
    description: "Breathable Lounge Night Dress",
    detailedDescription: "A breathable lounge night dress from Jockey, known for its superior comfort and quality. Perfect for relaxed evenings and comfortable sleep.",
    price: 760,
    image: womenpagenightwear5,
    category: "nightwear",
    offers: true,
    sizes: ["M", "L", "XL"],
    averageRating: 4.6,
    totalRatings: 100,
    customerReviews: [
      { id: 1, user: "Mona C.", rating: 5, review: "Jockey's fabric is always great. This dress is super comfortable." },
      { id: 2, user: "Gita P.", rating: 5, review: "Love the breathable material. Perfect for summer." },
      { id: 3, user: "Rahul T.", rating: 4, review: "Good quality nightwear, worth the price." },
    ],
    search_keywords: ["jockey", "nightwear", "breathable night dress", "lounge night dress", "comfortable sleepwear", "quality nightwear", "relaxed evenings nightwear", "womens night dress", "summer nightwear"],
  },

 

  // Dresses
  {
    id: 2041,
    name: "AND",
    description: "Floral Fit & Flare Dress",
    detailedDescription: "A beautiful floral fit & flare dress from AND, perfect for casual outings or semi-formal events. Features a flattering silhouette and vibrant floral print.",
    price: 1600,
    image: womenpagedress1,
    category: "dress",
    offers: true,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.5,
    totalRatings: 130,
    customerReviews: [
      { id: 1, user: "Ritu K.", rating: 5, review: "Love this dress! The fit is perfect and the print is so lively." },
      { id: 2, user: "Priyanka S.", rating: 4, review: "Great for summer, very comfortable. A bit short for my liking." },
      { id: 3, user: "Neha D.", rating: 4, review: "Stylish and flattering. Received many compliments." },
    ],
    search_keywords: ["and", "dress", "floral dress", "fit & flare dress", "casual dress", "semi-formal dress", "vibrant floral print", "summer dress", "womens dress", "party dress", "midi dress"],
  },
  {
    id: 2042,
    name: "Global Desi",
    description: "Ethnic Maxi Dress",
    detailedDescription: "An elegant ethnic maxi dress from Global Desi, perfect for a bohemian or festive look. Features traditional prints and a flowy silhouette for comfort and style.",
    price: 1450,
    image: womenpagedress2,
    category: "dress",
    offers: false,
    sizes: ["M", "L", "XL"],
    averageRating: 4.2,
    totalRatings: 110,
    customerReviews: [
      { id: 1, user: "Anjali V.", rating: 4, review: "Beautiful ethnic dress. Comfortable for long wear." },
      { id: 2, user: "Deepa N.", rating: 3, review: "The fabric is a bit sheer, but overall a nice dress." },
      { id: 3, user: "Smita P.", rating: 4, review: "Perfect for a casual Indian look. Very stylish." },
    ],
    search_keywords: ["global desi", "dress", "ethnic maxi dress", "bohemian dress", "festive dress", "traditional prints", "flowy dress", "comfortable dress", "stylish dress", "womens dress", "long dress"],
  },
  {
    id: 2043,
    name: "Zara",
    description: "Minimalist A-line Black Dress",
    detailedDescription: "A versatile minimalist A-line black dress from Zara, a timeless classic for any wardrobe. Can be dressed up or down for various occasions.",
    price: 1900,
    image: womenpagedress3,
    category: "dress",
    offers: true,
    sizes: ["XS", "S", "M", "L"],
    averageRating: 4.7,
    totalRatings: 90,
    customerReviews: [
      { id: 1, user: "Meera R.", rating: 5, review: "My go-to black dress! So chic and versatile." },
      { id: 2, user: "Kajal T.", rating: 5, review: "Zara's quality is evident. Fits perfectly." },
      { id: 3, user: "Rajesh K.", rating: 4, review: "A bit pricey for a simple dress, but the fabric and fit are great." },
    ],
    search_keywords: ["zara", "dress", "minimalist dress", "a-line dress", "black dress", "timeless dress", "versatile dress", "classic dress", "womens dress", "formal dress", "cocktail dress", "little black dress"],
  },
  {
    id: 2044,
    name: "Biba",
    description: "Casual Summer Cotton Dress",
    detailedDescription: "A comfortable casual summer cotton dress from Biba, perfect for everyday wear in warm weather. Light, breathable, and stylish.",
    price: 1300,
    image: womenpagedress4,
    category: "dress",
    offers: false,
    sizes: ["S", "M", "L", "XL"],
    averageRating: 4.3,
    totalRatings: 100,
    customerReviews: [
      { id: 1, user: "Poonam J.", rating: 4, review: "Nice everyday summer dress. Very comfortable cotton." },
      { id: 2, user: "Ankit V.", rating: 3, review: "Good for the price, but the color faded slightly after first wash." },
      { id: 3, user: "Radha C.", rating: 4, review: "Simple and elegant. Happy with the purchase." },
    ],
    search_keywords: ["biba", "dress", "casual dress", "summer dress", "cotton dress", "everyday wear dress", "light dress", "breathable dress", "stylish dress", "womens dress", "day dress"],
  },
  {
    id: 2045,
    name: "Only",
    description: "Layered Ruffle Midi Dress",
    detailedDescription: "A trendy layered ruffle midi dress from Only, perfect for a stylish and feminine look. Features delicate ruffles and a flattering midi length.",
    price: 1750,
    image: womenpagedress5,
    category: "dress",
    offers: true,
    sizes: ["XS", "S", "M", "L"],
    averageRating: 4.6,
    totalRatings: 85,
    customerReviews: [
      { id: 1, user: "Neha P.", rating: 5, review: "Love the ruffles! Very fashionable and comfortable." },
      { id: 2, user: "Vivek G.", rating: 4, review: "Bought for my sister, she really likes the style." },
      { id: 3, user: "Swati B.", rating: 4, review: "Great for parties and casual events. Good material." },
    ],
    search_keywords: ["only", "dress", "layered dress", "ruffle dress", "midi dress", "trendy dress", "feminine dress", "stylish dress", "party dress", "casual events dress", "womens dress"],
  },

 

  // Handbags
  {
    id: 2051,
    name: "Caprese",
    description: "Solid Textured Shoulder Bag",
    detailedDescription: "A chic solid textured shoulder bag from Caprese, perfect for everyday use. Features a stylish texture and enough space for your essentials.",
    price: 1200,
    image: womenpagehandbag1,
    category: "handbag",
    offers: true,
    sizes: ["OneSize"],
    averageRating: 4.4,
    totalRatings: 90,
    customerReviews: [
      { id: 1, user: "Rina D.", rating: 5, review: "Stylish and spacious. Love the texture and color." },
      { id: 2, user: "Pooja L.", rating: 4, review: "Good everyday bag. The strap is comfortable." },
      { id: 3, user: "Anjali S.", rating: 4, review: "Caprese always delivers. Good quality for the price." },
    ],
    search_keywords: ["caprese", "handbag", "shoulder bag", "solid bag", "textured bag", "everyday bag", "chic bag", "spacious bag", "womens handbag", "casual bag"],
  },
  {
    id: 2052,
    name: "Lavie",
    description: "Stylish Everyday Tote",
    detailedDescription: "A stylish everyday tote from Lavie, perfect for carrying all your essentials with ease. Features a spacious interior and a trendy design.",
    price: 980,
    image: womenpagehandbag2,
    category: "handbag",
    offers: false,
    sizes: ["OneSize"],
    averageRating: 4.1,
    totalRatings: 100,
    customerReviews: [
      { id: 1, user: "Smita B.", rating: 4, review: "Good for daily use, fits a lot of things." },
      { id: 2, user: "Kavita M.", rating: 3, review: "A bit flimsy compared to other Lavie bags I own." },
      { id: 3, user: "Rahul T.", rating: 4, review: "Bought as a gift, my sister liked it." },
    ],
    search_keywords: ["lavie", "handbag", "tote bag", "everyday tote", "stylish tote", "spacious tote", "trendy design bag", "womens handbag", "casual bag"],
  },
  {
    id: 2053,
    name: "Baggit",
    description: "Elegant Faux Leather Handbag",
    detailedDescription: "An elegant faux leather handbag from Baggit, combining style with ethical fashion. Features a sophisticated design and practical compartments.",
    price: 1450,
    image: womenpagehandbag3,
    category: "handbag",
    offers: true,
    sizes: ["OneSize"],
    averageRating: 4.5,
    totalRatings: 80,
    customerReviews: [
      { id: 1, user: "Divya N.", rating: 5, review: "Love that it's vegan and looks so elegant. Highly recommend Baggit." },
      { id: 2, user: "Arjun K.", rating: 4, review: "Good quality faux leather, looks like real leather." },
      { id: 3, user: "Priya P.", rating: 4, review: "Spacious and well-designed. Perfect for office." },
    ],
    search_keywords: ["baggit", "handbag", "faux leather handbag", "elegant handbag", "ethical fashion bag", "sophisticated design bag", "vegan bag", "womens handbag", "office bag", "party bag"],
  },
  {
    id: 2054,
    name: "Hidesign",
    description: "Classic Genuine Leather Bag",
    detailedDescription: "A timeless classic genuine leather bag from Hidesign, known for its superior craftsmanship and durable leather. A perfect blend of style and longevity.",
    price: 3200,
    image: womenpagehandbag4,
    category: "handbag",
    offers: false,
    sizes: ["OneSize"],
    averageRating: 4.8,
    totalRatings: 60,
    customerReviews: [
      { id: 1, user: "Suresh R.", rating: 5, review: "Hidesign never disappoints. The leather quality is superb." },
      { id: 2, user: "Sneha B.", rating: 5, review: "A true investment piece. It looks better with age." },
      { id: 3, user: "Varun D.", rating: 4, review: "Expensive, but the quality justifies the price. Very durable." },
    ],
    search_keywords: ["hidesign", "handbag", "genuine leather bag", "classic leather bag", "timeless bag", "superior craftsmanship bag", "durable bag", "investment bag", "womens handbag", "luxury bag"],
  },
  {
    id: 2055,
    name: "Zouk",
    description: "Vegan Handmade Office Bag",
    detailedDescription: "A unique vegan handmade office bag from Zouk, combining traditional Indian aesthetics with modern functionality. Perfect for daily office use.",
    price: 1350,
    image: womenpagehandbag5,
    category: "handbag",
    offers: true,
    sizes: ["OneSize"],
    averageRating: 4.6,
    totalRatings: 75,
    customerReviews: [
      { id: 1, user: "Kajal S.", rating: 5, review: "Love the Indian prints and it's vegan! Very practical for office." },
      { id: 2, user: "Rohit N.", rating: 4, review: "Good spacious bag, fits laptop and other essentials." },
      { id: 3, user: "Shalini K.", rating: 4, review: "Unique design and good quality. Happy to support a sustainable brand." },
    ],
    search_keywords: ["zouk", "handbag", "vegan bag", "handmade bag", "office bag", "indian aesthetics bag", "modern functionality bag", "sustainable bag", "womens handbag", "laptop bag", "work bag"],
  },
];
